export const PRIVACY_SCHEMA_CONTRACT_VERSION = '1.0.0' as const;

export const PRIVACY_SCHEMA_CONTRACT = {
  schema: 'onetime',
  tables: {
    privacy_consent_event: {
      purpose: 'append-only exact-Student, exact-scope, versioned consent evidence',
      required_columns: [
        'consent_event_id',
        'idempotency_key',
        'canonical_request_hash',
        'actor_kind',
        'actor_account_or_credential_id',
        'actor_adult_id',
        'household_id',
        'student_id',
        'relationship',
        'parent_authority_attested',
        'scope',
        'choice',
        'policy_versions',
        'occurred_at',
        'request_correlation_id',
        'network_evidence_digest',
        'supersedes_consent_event_id',
        'reason_code',
      ],
      unique_key: ['idempotency_key'],
    },
    recording_participant_snapshot: {
      purpose: 'immutable occurrence-start participant and consent evidence',
      required_columns: [
        'snapshot_id',
        'occurrence_id',
        'student_id',
        'household_id',
        'relationship',
        'snapshot_json',
        'created_at',
        'audit_ref',
      ],
      unique_key: ['occurrence_id', 'student_id'],
    },
    data_rights_request: {
      purpose: 'versioned verified privacy request and provider-cascade lifecycle',
      required_columns: [
        'request_id',
        'product',
        'runtime_tier',
        'verification_environment_id',
        'kind',
        'subject_json',
        'requester_kind',
        'requester_ref',
        'requester_household_id',
        'relationship_evidence',
        'recent_password_session_id',
        'state',
        'visible_status',
        'requested_categories',
        'excluded_categories',
        'legal_exception_codes',
        'provider_cascades',
        'dependent_review_required',
        'dependent_review_completed',
        'due_at',
        'completed_at',
        'terminal_reason_code',
        'version',
        'audit_refs',
      ],
      unique_key: ['request_id'],
    },
    export_download_grant: {
      purpose: 'hash-only one-use initiating-session-bound 15-minute download authorization',
      required_columns: [
        'grant_id',
        'request_id',
        'product',
        'runtime_tier',
        'verification_environment_id',
        'subject_binding_hash',
        'token_hash',
        'initiating_session_id',
        'issued_at',
        'expires_at',
        'used_at',
        'revoked_at',
        'version',
      ],
      unique_key: ['grant_id'],
    },
    privacy_retention_work: {
      purpose: 'fenced due work linked to a verified independent purge record',
      required_columns: [
        'work_id',
        'request_id',
        'subject_binding_hash',
        'category',
        'due_at',
        'legal_hold_codes',
        'provider_outbox_intents',
        'purge_record_digest',
        'state',
        'version',
      ],
      unique_key: ['work_id'],
    },
    purge_ledger_receipt: {
      purpose: 'primary-database receipt only; independent purge record remains outside backups',
      required_columns: [
        'ledger_event_id',
        'request_id',
        'record_digest',
        'primary_object_version_hash',
        'replica_object_version_hash',
        'replication_completed_at',
      ],
      unique_key: ['ledger_event_id'],
    },
  },
  required_invariants: [
    'consent and recording snapshots are append-only',
    'no date of birth, age, age band, grade, raw password, token, private body, media, or raw provider identifier is stored',
    'dependent Student privacy actions bind the current Parent and require separate review for data rights',
    'self-managed Student actions bind the exact Student and linked adult identity',
    'request transitions and versions are optimistic and fail closed',
    'data-rights requests and download grants persist one exact trusted product, runtime tier, and verification environment binding',
    'download grants inherit their request scope and preserve the composite request binding',
    'download authorization is hash-only, one-use, initiating-session-bound, and expires after exactly 15 minutes',
    'the primary database stores only independent-ledger receipts and cannot overwrite or delete purge records',
  ],
} as const;
