export const CLASSROOM_CORE_SCHEMA_CONTRACT_VERSION = 'P16-CLASSROOM-CORE-SCHEMA-001' as const;

export const CLASSROOM_CORE_REQUIRED_SCHEMA = {
  classSeries: {
    table: 'onetime.class_series',
    requiredColumns: [
      'class_series_key',
      'account_key',
      'product_key',
      'title',
      'series_state',
      'is_canonical',
      'timezone',
      'local_start_time',
      'duration_minutes',
      'recurrence_weekdays',
      'recurrence_starts_on',
      'recurrence_ends_on',
      'teacher_profile_key',
      'embedded_classroom_required',
      'recording_enabled',
      'version',
      'created_at',
      'updated_at',
    ],
    invariants: [
      'series_state is draft, active, paused, or archived',
      'exactly one active canonical series exists per account and product',
      'a newly created or restored noncanonical series is draft',
    ],
  },
  occurrences: {
    table: 'onetime.class_occurrences',
    requiredColumns: [
      'occurrence_key',
      'account_key',
      'product_key',
      'class_series_key',
      'local_class_date',
      'starts_at',
      'scheduled_ends_at',
      'join_opens_at',
      'join_closes_at',
      'occurrence_state',
      'schedule_version',
      'version',
      'created_at',
      'updated_at',
    ],
    invariants: [
      'unique account, product, series, and Jerusalem local class date',
      'occurrence_state supports scheduled, preparing, ready, live, completed, and canceled',
    ],
  },
  enrollments: {
    table: 'onetime.class_series_enrollments',
    requiredColumns: [
      'enrollment_key',
      'account_key',
      'product_key',
      'class_series_key',
      'learner_key',
      'household_key',
      'enrollment_state',
      'source',
      'effective_at',
      'revoked_at',
      'idempotency_key',
      'audit_ref',
      'version',
    ],
    invariants: [
      'unique account, product, series, and learner',
      'canonical enrollment is written in the Student lifecycle transaction',
    ],
  },
  commands: {
    table: 'onetime.classroom_core_commands',
    invariants: [
      'unique account, product, and idempotency key',
      'the same key with a different request hash is rejected',
    ],
  },
} as const;
