export const PROVIDER_CORE_SCHEMA_CONTRACT_VERSION = '1.0.0' as const;

export const PROVIDER_CORE_SCHEMA_CONTRACT = {
  schema: 'onetime',
  extends_table: 'job_outbox',
  tables: {
    provider_operation_binding: {
      purpose: 'exact non-secret provider registry/account binding for each ProviderOperation',
      required_columns: [
        'job_id',
        'registry_binding_key',
        'provider_account_ref_hash',
        'effect_kind',
        'household_id',
      ],
      unique_key: ['job_id'],
    },
    adult_ghl_identity_link: {
      purpose: 'adult-only GHL link, identity-review quarantine, and contact-level suppression',
      required_columns: [
        'adult_id',
        'normalized_email_hash',
        'state',
        'verified_contact_ref_hash',
        'candidate_contact_ref_hashes',
        'quarantined_outbox_intent_ids',
        'suppression_json',
        'version',
      ],
      unique_key: ['adult_id'],
    },
    household_provider_mapping: {
      purpose: 'household-keyed GHL record and household-scoped Stripe Customer correlation',
      required_columns: [
        'household_id',
        'owner_adult_id',
        'runtime_tier',
        'verification_environment_id',
        'billing_program',
        'ghl_household_record_ref_hash',
        'projected_owner_contact_ref_hash',
        'stripe_customer_ref_hash',
        'service_reminders_enabled',
        'lifecycle_state',
        'access_projection',
        'reconciliation_state',
        'transfer_target_contact_ref_hash',
        'provider_revision',
        'last_readback_digest',
        'version',
      ],
      unique_key: [
        'runtime_tier',
        'verification_environment_id',
        'household_id',
        'billing_program',
      ],
    },
    provider_readback_ledger: {
      purpose: 'append-only minimized canonical-account reconciliation evidence',
      required_columns: [
        'operation_id',
        'operation_version',
        'provider',
        'runtime_tier',
        'verification_environment_id',
        'provider_account_ref_hash',
        'disposition',
        'provider_resource_ref_hash',
        'reconciliation_digest',
        'observed_at',
      ],
      unique_key: ['operation_id', 'operation_version', 'reconciliation_digest'],
    },
  },
  required_invariants: [
    'Stripe ProviderOperations are signed-event ingestion or readback only and never mutation',
    'provider account, runtime tier, verification environment, request hash, and registry binding match before readback applies',
    'identity_review blocks only GHL projection, workflow, and billing effects',
    'one adult contact may own many distinct household mappings',
    'GHL household record and Stripe Customer references cannot be shared across households',
    'ownership transfer preserves household, GHL record, Stripe Customer, and financial identity',
    'readback is append-only and contains only protected references and digests',
  ],
} as const;
