export const JOB_FOUNDATION_SCHEMA_CONTRACT_VERSION = '1.0.0' as const;

export const JOB_FOUNDATION_SCHEMA_CONTRACT = {
  schema: 'onetime',
  tables: {
    job_command_idempotency: {
      purpose:
        'durable command replay/conflict record committed with local mutation and outbox intents',
      required_columns: [
        'product',
        'runtime_tier',
        'verification_environment_id',
        'actor_ref',
        'operation_scope',
        'idempotency_key',
        'canonical_request_hash',
        'response_json',
        'resulting_version',
        'outbox_job_ids',
        'created_at',
      ],
      unique_key: ['product', 'runtime_tier', 'actor_ref', 'operation_scope', 'idempotency_key'],
    },
    job_outbox: {
      purpose: 'one durable versioned ProviderOperation per logical external effect',
      required_columns: [
        'job_id',
        'operation_type',
        'aggregate_ref',
        'source_version',
        'provider',
        'product',
        'runtime_tier',
        'verification_environment_id',
        'idempotency_key',
        'canonical_request_hash',
        'payload_ref',
        'payload_digest',
        'compensation_for_job_id',
        'state',
        'version',
        'recovery_generation',
        'dispatch_attempts',
        'lifetime_dispatch_attempts',
        'reconciliation_attempts',
        'lease_owner',
        'lease_generation',
        'lease_expires_at',
        'last_heartbeat_at',
        'next_attempt_at',
        'unknown_effect',
        'provider_acceptance_digest',
        'reconciliation_digest',
        'safe_error_code',
        'created_at',
        'updated_at',
      ],
      unique_key: ['product', 'runtime_tier', 'verification_environment_id', 'idempotency_key'],
    },
  },
  required_invariants: [
    'canonical_request_hash and payload_digest are lowercase SHA-256 values',
    'the environment-to-runtime-tier mapping is enforced',
    'job state is one closed ProviderJobState value',
    'versions, generations, and counters are monotonic nonnegative integers',
    'unknown_effect is true exactly while mutating retry is quarantined',
    'lease updates and completions are fenced by owner, generation, expiry, and expected version',
    'compensation_for_job_id references a distinct original logical operation',
  ],
  required_indexes: [
    'due non-unknown work by scope, operation_type, state, next_attempt_at',
    'acceptance_unknown work by scope and updated_at',
    'aggregate_ref and source_version',
    'compensation_for_job_id',
  ],
} as const;
