import type {
  CommunicationWorkflowDefinition,
  CommunicationWorkflowFragment,
} from '../../../../../contracts/src/communications/foundation/index.ts';
import { COMMUNICATION_FOUNDATION_CONTRACT_VERSION } from '../../../../../contracts/src/communications/foundation/index.ts';
import { validateWorkflowFragment } from '../../foundation/index.ts';

const commonApprovalGates = [
  'registry_identity',
  'sender',
  'audience',
  'consent',
  'copy',
  'suppression',
] as const;

export const P30_CAMPAIGN_WORKFLOWS = [
  {
    workflow_key: 'OT-14',
    canonical_name: 'OT-14 Parent Newsletter',
    purpose: 'parent_newsletter',
    subject: 'adult_only',
    sender_key: 'rabbi_campaign',
    message_purpose: 'marketing',
    trigger: 'weekly Thursday at 12:00 household local time after explicit publication',
    ordered_steps: [
      'select current account owners with newsletter permission',
      'render the approved Rabbi note, class recap, schedule, recording or review, approved question highlight, and one CTA',
      'read back audience, suppression, sender, links, and rendered copy',
      'deliver one bounded operator seed through the release-verification harness',
      'hold the first broad send for named Rabbi or Admin approval',
      'recheck consent and suppression immediately before every email',
      'record dormant WhatsApp as channel_skipped_not_configured with zero provider calls',
    ],
    exit_conditions: [
      'newsletter permission withdrawn',
      'account owner no longer current',
      'send-time suppression',
      'publication paused',
      'weekly edition completed',
    ],
    idempotency_scope: 'OT-14:adult_id:household_local_week',
    approval_gates: [...commonApprovalGates, 'publication', 'broad_send'],
    requires_send_time_suppression_recheck: true,
    email_required: true,
    whatsapp_state: 'dormant',
    student_contact_prohibited: true,
  },
  {
    workflow_key: 'OT-15',
    canonical_name: 'OT-15 Former Member Reactivation',
    purpose: 'former_member_reactivation',
    subject: 'adult_only',
    sender_key: 'rabbi_campaign',
    message_purpose: 'marketing',
    trigger: 'named approval launch for the exact former-member segment',
    ordered_steps: [
      'validate all three canonical copy entries and exact content approvals',
      'send approved step 1 at approval launch',
      'wait 4 days and re-evaluate every exit and suppression condition',
      'send approved step 2',
      'wait 5 additional days and re-evaluate every exit and suppression condition',
      'send approved step 3 on day 9',
      'record dormant WhatsApp as channel_skipped_not_configured with zero provider calls',
    ],
    exit_conditions: [
      'signup completed',
      'active membership verified',
      'School classification present',
      'marketing permission withdrawn',
      'send-time suppression',
      'sequence completed',
    ],
    idempotency_scope: 'OT-15:adult_id:reactivation_campaign_version:step',
    approval_gates: [...commonApprovalGates, 'publication', 'broad_send'],
    requires_send_time_suppression_recheck: true,
    email_required: true,
    whatsapp_state: 'dormant',
    student_contact_prohibited: true,
  },
  {
    workflow_key: 'OT-16',
    canonical_name: 'OT-16 Free-Period Conversion',
    purpose: 'free_period_conversion',
    subject: 'adult_only',
    sender_key: 'office',
    message_purpose: 'marketing',
    trigger: '14, 7, 3, and 1 days before canonical free-period expiry and at expiry',
    ordered_steps: [
      'recompute and validate deterministic adult, expiry, and checkpoint operation identity',
      'resolve the exact canonical expiry and $67 USD monthly Family price',
      'exclude verified paid access, explicit decline, and custom School terms',
      'read back the approved adult-only Family audience',
      'recheck suppression immediately before each checkpoint',
      'refresh verified paid access, explicit decline, and custom School eligibility immediately before dispatch',
      'deliver the exact price, expiry, no-card, no-auto-charge, and Checkout CTA email',
      'record dormant WhatsApp as channel_skipped_not_configured with zero provider calls',
      'deduplicate by adult, expiry, and checkpoint',
    ],
    exit_conditions: [
      'verified active paid access',
      'explicit cancellation or decline',
      'send-time suppression where legally permitted',
      'custom School billing terms',
      'expiry checkpoint completed',
    ],
    idempotency_scope: 'OT-16:adult_id:expiry_at:checkpoint_days',
    approval_gates: [...commonApprovalGates, 'publication'],
    requires_send_time_suppression_recheck: true,
    email_required: true,
    whatsapp_state: 'dormant',
    student_contact_prohibited: true,
  },
] as const satisfies readonly CommunicationWorkflowDefinition[];

export const P30_CAMPAIGN_WORKFLOW_FRAGMENT = validateWorkflowFragment({
  contract_version: COMMUNICATION_FOUNDATION_CONTRACT_VERSION,
  owner_task: 'P30',
  fragment_id: 'P30-campaigns-v1',
  workflows: P30_CAMPAIGN_WORKFLOWS,
} satisfies CommunicationWorkflowFragment);
